Repository software-maestro-starting-blue/daily-painting, pull requests merged in 2024-06, with the labels that each got.

#3 [init] 프론트엔드, 백엔드 기본 코드 추가
  .gitignore
  backend/build.gradle
  backend/src/main/java/com/startingblue/dailypainting/diary/controller/DiaryController.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Diary.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/DiaryRepository.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Emotion.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/MetPeople.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Weather.java
  backend/src/main/java/com/startingblue/dailypainting/diary/service/DiaryService.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/controller/FeedbackController.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/domain/Feedback.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/domain/FeedbackRepository.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/service/FeedbackService.java
  backend/src/main/java/com/startingblue/dailypainting/member/controller/MemberController.java
  backend/src/main/java/com/startingblue/dailypainting/member/domain/Member.java
  backend/src/main/java/com/startingblue/dailypainting/member/domain/MemberRepository.java
  backend/src/main/java/com/startingblue/dailypainting/member/service/MemberService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/http.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Checkbox/Checkbox.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Text/Text.tsx
  frontend/src/constants/constant.ts
  frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
  frontend/src/pages/DiaryResultPage/DiaryResultPage.tsx
  frontend/src/pages/FeedbackPage/FeedbackPage.tsx
  frontend/src/styles/GlobalStyle.css
Labels: 백엔드, 프론트엔드

#6 feat: 일기 작성 API 개발
  backend/build.gradle
  backend/src/main/java/com/startingblue/dailypainting/config/AsyncConfig.java
  backend/src/main/java/com/startingblue/dailypainting/diary/controller/DiaryController.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Diary.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Emotion.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Gender.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/MetPeople.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/MetPerson.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Weather.java
  backend/src/main/java/com/startingblue/dailypainting/diary/dto/DiaryFormResponse.java
  backend/src/main/java/com/startingblue/dailypainting/diary/dto/DiarySaveRequest.java
  backend/src/main/java/com/startingblue/dailypainting/diary/dto/DiarySavedResponse.java
  backend/src/main/java/com/startingblue/dailypainting/diary/service/DiaryService.java
  backend/src/main/java/com/startingblue/dailypainting/openai/service/OpenAIService.java
  frontend/src/App.tsx
  frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
  frontend/tsconfig.json
Labels: 백엔드

#7 feat: 일기 확인 페이지 개발
  backend/src/main/java/com/startingblue/dailypainting/proxy/controller/ProxyController.java
  frontend/src/components/diaryresult/DiaryImageLayout/DiaryImageLayout.css
  frontend/src/components/diaryresult/DiaryImageLayout/DiaryImageLayout.tsx
  frontend/src/components/diaryresult/FeedbackRoutingButtonLayout/FeedbackRoutingButtonLayout.css
  frontend/src/components/diaryresult/FeedbackRoutingButtonLayout/FeedbackRoutingButtonLayout.tsx
  frontend/src/pages/DiaryResultPage/DiaryResultPage.css
  frontend/src/pages/DiaryResultPage/DiaryResultPage.tsx
Labels: 백엔드, 프론트엔드

#10 [feat] 그림 일기를 생성하는 로직을 구현
  .gitignore
  backend/src/main/java/com/startingblue/dailypainting/ai/service/AIDiaryService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/Dalle3VisionService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/DiaryConvertService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/Gpt4oSynarioService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/OpenAIAPIGenerator.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/PromptDiaryConvertService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/SynarioService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/VisionService.java
  backend/src/main/java/com/startingblue/dailypainting/diary/controller/DiaryController.java
  backend/src/main/java/com/startingblue/dailypainting/openai/service/OpenAIService.java
  backend/src/main/resources/application.properties
Labels: 백엔드

#8 [feat] 피드백 생성 페이지 구현
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/feedback/Comment.css
  frontend/src/components/feedback/Comment.tsx
  frontend/src/components/feedback/FavoriteCharacter.css
  frontend/src/components/feedback/FavoriteCharacter.tsx
  frontend/src/components/feedback/Rating.css
  frontend/src/components/feedback/Rating.tsx
  frontend/src/components/feedback/StarIcon.css
  frontend/src/components/feedback/StarIcon.tsx
  frontend/src/pages/FeedbackPage/FeedbackPage.css
  frontend/src/pages/FeedbackPage/FeedbackPage.tsx
Labels: 프론트엔드

#11 [feat] 사용자 일기 폼 페이지 개발
  frontend/src/components/ diaryform/BirthYearInput/BirthYearInput.css
  frontend/src/components/ diaryform/BirthYearInput/BirthYearInput.tsx
  frontend/src/components/ diaryform/DiaryContent/DiaryContent.css
  frontend/src/components/ diaryform/DiaryContent/DiaryContent.tsx
  frontend/src/components/ diaryform/EmotionSelectionLayout/EmotionSelectionLayout.css
  frontend/src/components/ diaryform/EmotionSelectionLayout/EmotionSelectionLayout.tsx
  frontend/src/components/ diaryform/GenderSelectionLayout/GenderSelectionLayout.css
  frontend/src/components/ diaryform/GenderSelectionLayout/GenderSelectionLayout.tsx
  frontend/src/components/ diaryform/MetPeopleSelectionLayout/MetPeopleSelection.tsx
  frontend/src/components/ diaryform/MetPeopleSelectionLayout/MetPeopleSelectionLayout.css
  frontend/src/components/ diaryform/SubmitButton/SubmitButton.css
  frontend/src/components/ diaryform/SubmitButton/SubmitButton.tsx
  frontend/src/components/ diaryform/WeatherSelectionLayout/WeatherSelectionLayout.css
  frontend/src/components/ diaryform/WeatherSelectionLayout/WeatherSelectionLayout.tsx
  frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
Labels: 프론트엔드

#12 [refactor] 긴급 수정
  backend/src/main/java/com/startingblue/dailypainting/config/WebConfig.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Emotion.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/MetPerson.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Weather.java
  backend/src/main/java/com/startingblue/dailypainting/member/controller/MemberController.java
  backend/src/main/java/com/startingblue/dailypainting/member/domain/Member.java
  backend/src/main/java/com/startingblue/dailypainting/member/domain/MemberRepository.java
  backend/src/main/java/com/startingblue/dailypainting/member/exception/MemberException.java
  backend/src/main/java/com/startingblue/dailypainting/member/service/MemberService.java
  frontend/src/components/diaryform/BirthYearInput/BirthYearInput.css
  frontend/src/components/diaryform/BirthYearInput/BirthYearInput.tsx
  frontend/src/components/diaryform/DiaryContent/DiaryContent.css
  frontend/src/components/diaryform/DiaryContent/DiaryContent.tsx
  frontend/src/components/diaryform/EmotionSelectionLayout/EmotionSelectionLayout.css
  frontend/src/components/diaryform/EmotionSelectionLayout/EmotionSelectionLayout.tsx
  frontend/src/components/diaryform/GenderSelectionLayout/GenderSelectionLayout.css
  frontend/src/components/diaryform/GenderSelectionLayout/GenderSelectionLayout.tsx
  frontend/src/components/diaryform/MetPeopleSelectionLayout/MetPeopleSelectionLayout.css
  frontend/src/components/diaryform/MetPeopleSelectionLayout/MetPeopleSelectionLayout.tsx
  frontend/src/components/diaryform/SubmitButton/SubmitButton.css
  frontend/src/components/diaryform/SubmitButton/SubmitButton.tsx
  frontend/src/components/diaryform/WeatherSelectionLayout/WeatherSelectionLayout.css
  frontend/src/components/diaryform/WeatherSelectionLayout/WeatherSelectionLayout.tsx
  frontend/src/components/diaryform/icon/emotion/ANGRY.png
  frontend/src/components/diaryform/icon/emotion/ANNOYED.png
  frontend/src/components/diaryform/icon/emotion/ANTICIPATING.png
  frontend/src/components/diaryform/icon/emotion/ANXIOUS.png
  frontend/src/components/diaryform/icon/emotion/DEFAULT.png
  frontend/src/components/diaryform/icon/emotion/DEPRESSED.png
  frontend/src/components/diaryform/icon/emotion/EXCITED.png
  frontend/src/components/diaryform/icon/emotion/MOTIVATED.png
  frontend/src/components/diaryform/icon/emotion/PRESSURED.png
  frontend/src/components/diaryform/icon/emotion/PROUD.png
  frontend/src/components/diaryform/icon/emotion/REFRESHING.png
  frontend/src/components/diaryform/icon/emotion/SAD.png
  frontend/src/components/diaryform/icon/emotion/THRILLED.png
  frontend/src/components/diaryform/icon/metperson/ACQUAINTANCE.png
  frontend/src/components/diaryform/icon/metperson/DEFAULT.png
  frontend/src/components/diaryform/icon/metperson/FAMILY.png
  frontend/src/components/diaryform/icon/metperson/FRIEND.png
  frontend/src/components/diaryform/icon/metperson/LONELY.png
  frontend/src/components/diaryform/icon/metperson/LOVER.png
  frontend/src/components/diaryform/icon/metperson/NO_ONE.png
  frontend/src/components/diaryform/icon/weather/CLEAR.png
  frontend/src/components/diaryform/icon/weather/CLOUDY.png
  frontend/src/components/diaryform/icon/weather/COLD_WAVE.png
  frontend/src/components/diaryform/icon/weather/DEFAULT.png
  frontend/src/components/diaryform/icon/weather/HEATWAVE.png
  frontend/src/components/diaryform/icon/weather/RAIN.png
  frontend/src/components/diaryform/icon/weather/SNOW.png
  frontend/src/components/diaryform/icon/weather/TYPHOON.png
  frontend/src/components/diaryform/icon/weather/WINDY.png
  frontend/src/components/diaryform/icon/weather/YELLOW_DUST.png
  frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
Labels: 백엔드, 버그, 프론트엔드

#13 feat: 라우팅 추가, fix: 자잘한 버그 수정
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Emotion.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/MetPerson.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Weather.java
  backend/src/main/java/com/startingblue/dailypainting/proxy/controller/ProxyController.java
  frontend/src/App.tsx
  frontend/src/components/ diaryform/BirthYearInput/BirthYearInput.css
  frontend/src/components/ diaryform/BirthYearInput/BirthYearInput.tsx
  frontend/src/components/ diaryform/DiaryContent/DiaryContent.css
  frontend/src/components/ diaryform/DiaryContent/DiaryContent.tsx
  frontend/src/components/ diaryform/EmotionSelectionLayout/EmotionSelectionLayout.css
  frontend/src/components/ diaryform/EmotionSelectionLayout/EmotionSelectionLayout.tsx
  frontend/src/components/ diaryform/GenderSelectionLayout/GenderSelectionLayout.css
  frontend/src/components/ diaryform/GenderSelectionLayout/GenderSelectionLayout.tsx
  frontend/src/components/ diaryform/MetPeopleSelectionLayout/MetPeopleSelection.tsx
  frontend/src/components/ diaryform/MetPeopleSelectionLayout/MetPeopleSelectionLayout.css
  frontend/src/components/ diaryform/SubmitButton/SubmitButton.css
  frontend/src/components/ diaryform/SubmitButton/SubmitButton.tsx
  frontend/src/components/ diaryform/WeatherSelectionLayout/WeatherSelectionLayout.css
  frontend/src/components/ diaryform/WeatherSelectionLayout/WeatherSelectionLayout.tsx
  frontend/src/components/diaryform/DiaryContent/DiaryContent.tsx
  frontend/src/index.tsx
  frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
  frontend/src/pages/DiaryResultPage/DiaryResultPage.tsx
  frontend/src/pages/FeedbackPage/FeedbackPage.tsx
Labels: 백엔드, 버그, 프론트엔드
