Repository software-maestro-starting-blue/daily-painting, pull requests merged in 2024-07, with the labels that each got.

#15 [refactor] DiaryResultPage 컨벤션 재점검 및 수정
  frontend/src/components/diaryresult/DiaryImageLayout/DiaryImageLayout.css
  frontend/src/components/diaryresult/DiaryImageLayout/DiaryImageLayout.tsx
  frontend/src/components/diaryresult/FeedbackRoutingButtonLayout/FeedbackRoutingButtonLayout.css
  frontend/src/components/diaryresult/FeedbackRoutingButtonLayout/FeedbackRoutingButtonLayout.tsx
  frontend/src/pages/DiaryResultPage/DiaryResultPage.css
  frontend/src/pages/DiaryResultPage/DiaryResultPage.tsx
Labels: 프론트엔드

#16 [feat][refactor] AI 서비스 테스트 코드 작성 & 리팩토링 & 예외 처리
  backend/src/main/java/com/startingblue/dailypainting/ai/exception/AIError.java
  backend/src/main/java/com/startingblue/dailypainting/ai/exception/AIErrorResponse.java
  backend/src/main/java/com/startingblue/dailypainting/ai/exception/AIExceptionControllerAdvice.java
  backend/src/main/java/com/startingblue/dailypainting/ai/exception/JsonAIError.java
  backend/src/main/java/com/startingblue/dailypainting/ai/exception/OpenAIError.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/AIDiaryService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/DiaryConvertService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/OpenAIAPIGenerator.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/PromptDiaryConvertService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/SynarioService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/VisionService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/scenario/Gpt4oScenarioService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/scenario/ScenarioService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/vision/Dalle3VisionService.java
  backend/src/main/java/com/startingblue/dailypainting/ai/service/vision/VisionService.java
  backend/src/test/java/com/startingblue/dailypainting/ai/service/AIDiaryServiceTest.java
  backend/src/test/java/com/startingblue/dailypainting/ai/service/DiaryConvertServiceTest.java
  backend/src/test/java/com/startingblue/dailypainting/ai/service/OpenAIAPIGeneratorTest.java
  backend/src/test/java/com/startingblue/dailypainting/ai/service/scenario/ScenarioServiceTest.java
  backend/src/test/java/com/startingblue/dailypainting/ai/service/vision/VisionServiceTest.java
Labels: 백엔드

#18 feat : 일기 입력 페이지 개인정보 수락 동의, 입력 페이지 검증 기능 기능 구현
  frontend/src/components/common/Checkbox/Checkbox.css
  frontend/src/components/common/Checkbox/Checkbox.tsx
  frontend/src/components/diaryform/BirthYearInput/BirthYearInput.css
  frontend/src/components/diaryform/BirthYearInput/BirthYearInput.tsx
  frontend/src/components/diaryform/DiaryContent/DiaryContent.css
  frontend/src/components/diaryform/DiaryContent/DiaryContent.tsx
  frontend/src/components/diaryform/EmotionSelectionLayout/EmotionSelectionLayout.css
  frontend/src/components/diaryform/EmotionSelectionLayout/EmotionSelectionLayout.tsx
  frontend/src/components/diaryform/GenderSelectionLayout/GenderSelectionLayout.css
  frontend/src/components/diaryform/GenderSelectionLayout/GenderSelectionLayout.tsx
  frontend/src/components/diaryform/MetPeopleSelectionLayout/MetPeopleSelectionLayout.css
  frontend/src/components/diaryform/MetPeopleSelectionLayout/MetPeopleSelectionLayout.tsx
  frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.css
  frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.tsx
  frontend/src/components/diaryform/SubmitButton/SubmitButton.css
  frontend/src/components/diaryform/SubmitButton/SubmitButton.tsx
  frontend/src/components/diaryform/WeatherSelectionLayout/WeatherSelectionLayout.css
  frontend/src/components/diaryform/WeatherSelectionLayout/WeatherSelectionLayout.tsx
  frontend/src/pages/DiaryFormPage/DiaryFormPage.css
  frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
Labels: 프론트엔드

#19 feat : Diary 커스텀 예외 기능, 검증 기능 추가
  backend/src/main/java/com/startingblue/dailypainting/diary/controller/DiaryController.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Diary.java
  backend/src/main/java/com/startingblue/dailypainting/diary/dto/DiarySaveRequest.java
  backend/src/main/java/com/startingblue/dailypainting/diary/exception/DiaryException.java
  backend/src/main/java/com/startingblue/dailypainting/diary/exception/DiaryExceptionControllerAdvice.java
  backend/src/main/java/com/startingblue/dailypainting/diary/exception/ErrorResponse.java
  backend/src/main/java/com/startingblue/dailypainting/diary/service/DiaryService.java
  backend/src/test/java/com/startingblue/dailypainting/diary/domain/DiaryTest.java
Labels: 백엔드

#17 [feat] 피드백 감사 페이지 구현
  frontend/src/App.tsx
  frontend/src/components/feedback/StarIcon.tsx
  frontend/src/components/feedback/comment/Comment.css
  frontend/src/components/feedback/comment/Comment.tsx
  frontend/src/components/feedback/favoritecharacter/FavoriteCharacter.css
  frontend/src/components/feedback/favoritecharacter/FavoriteCharacter.tsx
  frontend/src/components/feedback/rating/Rating.css
  frontend/src/components/feedback/rating/Rating.tsx
  frontend/src/components/feedback/staricon/StarIcon.css
  frontend/src/components/feedback/staricon/StarIcon.tsx
  frontend/src/pages/FeedbackPage/FeedbackPage.tsx
  frontend/src/pages/FeedbackThanksPage/FeedbackThanksPage.css
  frontend/src/pages/FeedbackThanksPage/FeedbackThanksPage.tsx
Labels: 프론트엔드

#20 [refactor] 커스텀 예외 추가, 도메인의 필드를 VO로 변경
  backend/src/main/java/com/startingblue/dailypainting/diary/exception/DiaryNotFoundException.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/domain/Feedback.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/domain/vo/Comment.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/domain/vo/Event.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/domain/vo/FavoriteCharacter.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/domain/vo/ImageQuality.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/domain/vo/ImageSatisfaction.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/domain/vo/ServiceSatisfaction.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/dto/FeedbackSaveRequest.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/exception/CommentLengthOverException.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/exception/FavoriteCharacterLengthOverException.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/exception/FeedbackException.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/exception/ImageQualityValueException.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/exception/ImageSatisfactionValueException.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/exception/ServiceSatisfactionValueException.java
  backend/src/main/java/com/startingblue/dailypainting/feedback/service/FeedbackService.java
  backend/src/test/java/com/startingblue/dailypainting/feedback/domain/FeedbackTest.java
  backend/src/test/java/com/startingblue/dailypainting/feedback/service/FeedbackServiceTest.java
Labels: 백엔드

#24 [merge] Develop to Main Merge for 1st mvp
  backend/src/main/java/com/startingblue/dailypainting/config/WebConfig.java
Labels: 백엔드, 버그

#22 [feat] 피드백 페이지 디자인 리팩토링, 이벤트 참여용 입력폼, 동의 추가
  frontend/src/components/feedback/AgreementLayout/AgreementLayout.css
  frontend/src/components/feedback/AgreementLayout/AgreementLayout.tsx
  frontend/src/components/feedback/eventformlayout/EventFormLayout.css
  frontend/src/components/feedback/eventformlayout/EventFormLayout.tsx
  frontend/src/components/feedback/phonenumber/PhoneNumber.css
  frontend/src/components/feedback/phonenumber/PhoneNumber.tsx
  frontend/src/pages/FeedbackPage/FeedbackPage.css
  frontend/src/pages/FeedbackPage/FeedbackPage.tsx
Labels: 프론트엔드

#29 [feat] S3 저장 기능 추가
  backend/build.gradle
  backend/src/main/java/com/startingblue/dailypainting/config/S3Config.java
  backend/src/main/java/com/startingblue/dailypainting/diary/controller/DiaryController.java
  backend/src/main/java/com/startingblue/dailypainting/diary/service/DiaryService.java
Labels: 백엔드

#28 feat & fix: 아이콘 추가, 일기 선택 정보 한글로 보내고 받기, 일기 작성 관련 버그 수정
  backend/src/main/java/com/startingblue/dailypainting/diary/controller/DiaryController.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Emotion.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/MetPerson.java
  backend/src/main/java/com/startingblue/dailypainting/diary/domain/Weather.java
  backend/src/main/java/com/startingblue/dailypainting/diary/dto/DiaryFormResponse.java
  frontend/src/App.css
  frontend/src/components/diaryform/BirthYearInput/BirthYearInput.tsx
  frontend/src/components/diaryform/DiaryContent/DiaryContent.css
  frontend/src/components/diaryform/EmotionSelectionLayout/EmotionSelectionLayout.tsx
  frontend/src/components/diaryform/GenderSelectionLayout/GenderSelectionLayout.tsx
  frontend/src/components/diaryform/MetPeopleSelectionLayout/MetPeopleSelectionLayout.tsx
  frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.css
  frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.tsx
  frontend/src/components/diaryform/SubmitButton/SubmitButton.tsx
  frontend/src/components/diaryform/WeatherSelectionLayout/WeatherSelectionLayout.tsx
  frontend/src/components/diaryform/icon/emotion/HAPPY.png
  frontend/src/components/diaryform/icon/emotion/LONELY.png
  frontend/src/components/diaryform/icon/emotion/RELAXED.png
  frontend/src/components/diaryform/icon/emotion/TIRED.png
  frontend/src/components/diaryform/icon/metperson/ACQUAINTANCE.png
  frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
Labels: 백엔드, 프론트엔드

#32 [fix] 이미지 표시 디자인 레이아웃 수정
  frontend/src/components/diaryresult/DiaryImageLayout/DiaryImageLayout.css
  frontend/src/components/diaryresult/DiaryImageLayout/DiaryImageLayout.tsx
Labels: 프론트엔드
